spring.application.name=chat-bot

server.port=8080
server.servlet.context-path=/api


spring.ai.chat.client.enabled=false

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=phi3.5
spring.ai.ollama.chat.options.temperature=0.7


spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.api-key=${openai_api_key}
spring.ai.openai.chat.options.model=openai/gpt-oss-20b:free


